### PR TITLE
feat: add ability to use line breaks in labels

### PR DESCRIPTION
**Pull request by axolotlmaid**
## Changes
- Changed Entry to TextView in LabelEditor.py
- Removed placeholder text
- Added CSS entries to make the TextView fit in

## Images
2024-06-28-221936_hyprshot
2024-06-28-221923_hyprshot

### CODE REVIEW

**Comment by Core447** [comment]
Nice work! I'll try this when I have some time

**Comment by Core447** [comment]
I changed the design a bit. The only thing bothering me is that the TextView has no placeholder support...

**Comment by axolotlmaid** [comment]
> I changed the design a bit. The only thing bothering me is that the TextView has no placeholder support...

Yeah, that is why i had to remove the placeholder text. You can technically add line breaks to a label without a TextView but I think it looks a bit weird where instead of adding new lines in the Entry widget it just adds this weird arrow symbol.

**Comment by Core447** [comment]
I'll play around with different concepts for this when I have some time

**Comment by gensyn** [comment]
> I'll play around with different concepts for this when I have some time

Do you have a branch with your changed design? I don't see a fittting name in the StreamController branches.

**Comment by Core447** [comment]
So far it's just the one commit (fb00101a0ffd4300268d5e11e80e00cc96108dfc) that I made to this PR. I definately want to keep some sort of placeholder. What do you think about simply allowing \n in the currently used entry box?

**Comment by gensyn** [comment]
> So far it's just the one commit ([fb00101](https://github.com/StreamController/StreamController/commit/fb00101a0ffd4300268d5e11e80e00cc96108dfc)) that I made to this PR. I definately want to keep some sort of placeholder. What do you think about simply allowing \n in the currently used entry box?

Would be fine by me. Though I would like to mention that I asked ChatGPT about the placeholder issue with TextView and it suggested to handle it ourselves like this:

```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk

class MainWindow(Gtk.Window):
    def init(self):
        Gtk.Window.init(self, title="TextView with Placeholder Example")
        self.set_default_size(400, 300)

        # VBox to arrange widgets vertically
        vbox = Gtk.VBox(spacing=6)
        self.add(vbox)

        # Button to replace the entry with a TextView
        self.button = Gtk.Button(label="Replace with TextView")
        self.button.connect("clicked", self.on_button_clicked)
        vbox.pack_start(self.button, False, False, 0)

        # Initial single-line text entry
        self.entry = Gtk.Entry()
        self.entry.set_text("This is a single-line entry")
        vbox.pack_start(self.entry, False, False, 0)

        # Container for the TextView (will be shown later)
        self.textview_scrolled_window = Gtk.ScrolledWindow()
        self.textview = Gtk.TextView()
        self.textview_scrolled_window.add(self.textview)
        self.textview_scrolled_window.set_vexpand(True)

        # Placeholder text
        self.placeholder_text = "Enter your text here..."
        self.is_placeholder_visible = False

    def on_button_clicked(self, widget):
        # Transfer text from Entry to TextView
        entry_text = self.entry.get_text()
        text_buffer = self.textview.get_buffer()
        text_buffer.set_text(entry_text)

        # Remove Entry and show TextView in the scrolled window
        parent = self.entry.get_parent()
        parent.remove(self.entry)
        parent.pack_start(self.textview_scrolled_window, True, True, 0)
        self.textview_scrolled_window.show_all()

        # Connect signals for placeholder management
        self.textview.connect("focus-in-event", self.on_textview_focus_in)
        self.textview.connect("focus-out-event", self.on_textview_focus_out)

        # Set placeholder if TextView is empty
        if text_buffer.get_text(text_buffer.get_start_iter(), text_buffer.get_end_iter(), True) == "":
            self.set_placeholder()

        # Disable the button since replacement is already done
        self.button.set_sensitive(False)

    def set_placeholder(self):
        buffer = self.textview.get_buffer()
        buffer.set_text(self.placeholder_text)
        self.textview.modify_fg(Gtk.StateFlags.NORMAL, Gdk.color_parse("gray"))
        self.is_placeholder_visible = True

    def remove_placeholder(self):
        buffer = self.textview.get_buffer()
        buffer.set_text("")
        self.textview.modify_fg(Gtk.StateFlags.NORMAL, None) # Reset to default color
        self.is_placeholder_visible = False

    def on_textview_focus_in(self, widget, event):
        if self.is_placeholder_visible:
            self.remove_placeholder()

    def on_textview_focus_out(self, widget, event):
        buffer = self.textview.get_buffer()
        text = buffer.get_text(buffer.get_start_iter(), buffer.get_end_iter(), True)
        if text.strip() == "":
            self.set_placeholder()

win = MainWindow()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()
```

**Comment by Core447** [comment]
That doesn't work for me, I just get a white window. (and it's gtk3)

**Comment by gensyn** [comment]
Well yeah, ChatGPT rarely spits out code that just works. It was more meant as concept.

Put in grey placeholder text by default and when entering the TextView check if the text is the placeholder - if yes, remove it. On leaving the TextView, check whether it is empty and if yes, readd the placeholder.

**Comment by Core447** [comment]
> Put in grey placeholder text by default and when entering the TextView check if the text is the placeholder - if yes, remove it. On leaving the TextView, check whether it is empty and if yes, readd the placeholder.

But if the user want to have the placeholder text as the actual text...

**Comment by gensyn** [comment]
:laughing: 
I feel like having
```
Label line 1
Label line 2
```
as a placeholder is a safe bet. As a workaround, people who reeeealy want that text could add an extra space.

**Comment by Core447** [comment]
I hope I'm not annoying, but I really don't want to just bet that no one will use the placeholder. If there's no way to add a placeholder via some workaround, I think we should use the `\n` option

**Comment by gensyn** [comment]
By now it seems like you are looking for reason not to use TextView.
If you wanted to, you could save a boolean if the text in the TextView was set automatically or by the user and there are probably a couple of other solutions as well. And as I said, I don't really care either way

**Comment by Core447** [comment]
I don't have anything against TextView, but I hope you can understand that I want to keep the placeholder. However, I'll try to find a nice workaround for the placeholder

**Comment by Core447** [comment]
@gensyn What do you think about this placeholder solution?

**Comment by gensyn** [comment]
I played around with it a bit and it seems to be working good. Once I got to a point to where the TextView would only display one line although there were several but I couldn't reproduce it. Looks good.

**Comment by gensyn** [comment]
But maybe the color button should have a fixed height - that looks a little weird when it stretches.

**Comment by Core447** [comment]
> But maybe the color button should have a fixed height - that looks a little weird when it stretches.

image
Without stretching it looks weird too...

**Comment by gensyn** [comment]
True.

**Comment by Core447** [comment]
> True.

And while the stretched button also looks kinda weird, it at least makes sense, because it controls the color of all lines. However, maybe moving it below the textview makes sense

**Comment by gensyn** [comment]
Then it could better line up with the new outline row. Sounds like a good idea.

**Comment by gensyn** [comment]
I was actually thinking that font and color could share a line like oultine width and outline color do. That way, both color pickers would be next to each other. I thought that might look tidier.

**Comment by Core447** [comment]
I think I would make every property take one line, separating outline width and outline color. What do you think?

**Comment by gensyn** [comment]
Yeah, sure, as long as it's consistent.

**Comment by gensyn** [comment]
That works for me.

**Comment by Core447** [comment]
It takes up quite a lot of space, but it's consistent now.

There's just one problem left: When there's a multi-line label in the textview and the revert/reset button is pressed the text gets cleared as expected, but the height doesn't shrink.

**Comment by gensyn** [comment]
Not always, but sometimes the height does get reset. I assume it's a race condition between deleting the text and the focus lost event of the TextView or something like that.

**Comment by gensyn** [comment]
I think this a minor cosmetic problem which wouldn't bother me if everything else works. So I would just go with it instead of leaving this PR in limbo.

**Comment by Core447** [comment]
The problem is that users will think it's a bug, which it kinda is, so I'll try to fix this in coming days and if I can't fix it, I'm gonna merge it

**Comment by Core447** [comment]
I still haven't found a way around this, what do you think about a toggle for this feature in the settings so that the users will get informed about this "bug" and don't report it?

**Comment by gensyn** [comment]
Yeah, that sounds reasonable. Although I suspect that instead user will keep asking for this feature because it's hidden. 🙃

**Comment by axolotlmaid** [comment]
> Yeah, that sounds reasonable. Although I suspect that instead user will keep asking for this feature because it's hidden. 🙃

What about adding an experimental section in the first start up page?

**Comment by Core447** [comment]
> What about adding an experimental section in the first start up page?

The problem with this is that it can't be changed later on because there's no way to open the onboarding dialog a second time.

**Pull request merged**
