### PR TITLE
fix: show_error is on ControllerKey, not ControllerKeyState

### PR DESCRIPTION
**Pull request by Sorunome**

### CODE REVIEW

**Comment by Core447** [comment]
Thanks for the great work! However, it might make more sense to actually handle the error icon separately for all states, what do you think?

**Comment by Sorunome** [comment]
While that does make sense, it also sounds like a different thing that this pr does; this pr fixes the status quo, the other thing would be an enhancement

30. 5. 2024 20:54:38 Core447 ***@***.***>:

**Comment by Sorunome** [comment]
Superseded by #124, there it is also on the state

**Comment by Core447** [comment]
Ok, then I'm going to add this to the state

**Pull request closed without merging**
