### PR TITLE
Feat(GtkHelper): Added an IpEntryRow

### PR DESCRIPTION
**Pull request by G4PLS**
This makes it easier for the User to enter an Ip Address. It does not check if an ip address is valid, this needs to be done seperately

The row itself looks like this:
image

It implements a custom event called 'ip-changed' which triggers whenever any of the entries get changed. This event has 2 args:
- arg1: Event Caller
- arg2: New IP Address as a string

It also has a custom type called 'IpEntryRow'

### CODE REVIEW

**Comment by G4PLS** [comment]
Split the Row up and added a NetworkRow containing the IpEntryRow and HostnameEntryRow
Create a IpEntryRow and a HostnameEntryRow which contain the Ui and methods to work out of the box.

Made the HostnameEntryRow only emit the changed signal when enter is pressed and not on every letter that gets changed. Wanted to add focus-out-event aswell so it gets emitted when the user is "finished" but event somehow doesnt exist.

The whole row now looks like this:
image

**Comment by Core447** [comment]
Great work! I'm wondering, though: What is the benefit over an EntryRow? I don't want to sound mean, I just want to know how you came up with the idea.

**Comment by G4PLS** [comment]
I personally think it looks a lot cleaner so its more of a Visual decision i made
I want to add some features like auto focus swapping when entering a Dot

**Comment by G4PLS** [comment]
I created a new branch and when the features are finished would love to merge from there. Wanted to keep my main free and wasnt able to change it in here.
New PR is #190

**Pull request closed without merging**
