### PR TITLE
Housekeeping: keep page backups for one week at most

### PR DESCRIPTION
**Pull request by gensyn**
As the backup count for pages quickly rises (I have deleted several hundred backup folders; power users probably have more), I have added a mechanism to clean them up. Backup folders are now deleted after one week - but at least three backup folders are always kept.

### CODE REVIEW

**Comment by Core447** [comment]
Thanks!

What do you think about this? I think having the removal code in the PageManagerBackend makes a lot more sense, because this is where they get generated and checking for old backups for each page backup is very resource heavy.

**Comment by gensyn** [comment]
To be honest, I was a little confused by which backups were created where. As long as it works now I'm fine. Code looks good.

**Comment by gensyn** [comment]
But you are just keeping a fixed number of backups, right? No check for the age of a backup?

**Comment by Core447** [comment]
> But you are just keeping a fixed number of backups, right? No check for the age of a backup?

Yes, what is the advantage of checking the age? In theory only keeping one backup should be enough, but just to be sure I set it to 5 (+1).

**Comment by gensyn** [comment]
Well, you suggested one week as a time period when we talked about it on Discord so I just went with it since it's definitely better than the status quo. But it's even better now so I'm all for merging.

**Comment by Core447** [comment]
Ok, sorry, I forgot I said that.

**Pull request merged**
