### PR TITLE
Added option to change the outline color of labels

### PR DESCRIPTION
**Pull request by gensyn**

### CODE REVIEW

**Comment by Core447** [comment]
Great job! We just need a revert button for the outline width spinner (similar to the size spinners in the layout area). And we should add arguments to `set_label` of `ActionBase` to set defaults for the new options

**Comment by gensyn** [comment]
On it.

**Comment by gensyn** [comment]
Ok, added both.

**Comment by Core447** [comment]
Thank you!

**Comment by gensyn** [comment]
Thanks for adding the last tweaks

**Comment by Core447** [comment]
No problem!

**Pull request merged**
